"""Vehicle Management

Revision ID: d21452b97b77
Revises: 
Create Date: 2026-07-11 20:03:18.328609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd21452b97b77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('rfid_uid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('vehicle_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('vehicle_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_index(batch_op.f('rfid_tag'))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('rfid_tag')
        batch_op.drop_column('owner_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('rfid_tag', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('rfid_tag'), ['rfid_tag'], unique=True)
        batch_op.alter_column('vehicle_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('vehicle_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('rfid_uid')
        batch_op.drop_column('color')
        batch_op.drop_column('model')
        batch_op.drop_column('brand')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
